package br.com.sysconfer.entities;

// Generated 23/11/2014 15:07:24 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Eventos generated by hbm2java
 */
public class Eventos implements java.io.Serializable {

	private Integer idEventos;
	private String descricao;
	private Date dtInicio;
	private Date dtFim;

	public Eventos() {
	}

	public Eventos(String descricao, Date dtInicio) {
		this.descricao = descricao;
		this.dtInicio = dtInicio;
	}

	public Eventos(String descricao, Date dtInicio, Date dtFim) {
		this.descricao = descricao;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
	}

	public Integer getIdEventos() {
		return this.idEventos;
	}

	public void setIdEventos(Integer idEventos) {
		this.idEventos = idEventos;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

}
