package br.com.sysconfer.entities;

// Generated 29/11/2014 04:56:58 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eventos generated by hbm2java
 */
@Entity
@Table(name = "Eventos")
public class Eventos implements java.io.Serializable {

	private static final long serialVersionUID = 1044532507401553133L;
	private Integer idEventos;
	private String descricao;
	private Date dtInicio;
	private Date dtFim;

	public Eventos() {
	}

	public Eventos(String descricao, Date dtInicio) {
		this.descricao = descricao;
		this.dtInicio = dtInicio;
	}

	public Eventos(String descricao, Date dtInicio, Date dtFim) {
		this.descricao = descricao;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEventos", unique = true, nullable = false)
	public Integer getIdEventos() {
		return this.idEventos;
	}

	public void setIdEventos(Integer idEventos) {
		this.idEventos = idEventos;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtInicio", nullable = false, length = 19)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtFim", length = 19)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

}
