package br.com.sysconfer.entities;

// Generated 23/11/2014 15:07:24 by Hibernate Tools 4.3.1

/**
 * Funcionalidades generated by hbm2java
 */
public class Funcionalidades implements java.io.Serializable {

	private Integer idFuncionalidades;
	private String descricao;

	public Funcionalidades() {
	}

	public Funcionalidades(String descricao) {
		this.descricao = descricao;
	}

	public Integer getIdFuncionalidades() {
		return this.idFuncionalidades;
	}

	public void setIdFuncionalidades(Integer idFuncionalidades) {
		this.idFuncionalidades = idFuncionalidades;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
