package br.com.sysconfer.entities;

// Generated 29/11/2014 04:56:58 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Funcionalidades generated by hbm2java
 */
@Entity
@Table(name = "Funcionalidades", catalog = "sysconfer")
public class Funcionalidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7898207023635066980L;
	private Integer idFuncionalidades;
	private String descricao;

	public Funcionalidades() {
	}

	public Funcionalidades(String descricao) {
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFuncionalidades", unique = true, nullable = false)
	public Integer getIdFuncionalidades() {
		return this.idFuncionalidades;
	}

	public void setIdFuncionalidades(Integer idFuncionalidades) {
		this.idFuncionalidades = idFuncionalidades;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
