package br.com.sysconfer.entities;

// Generated 23/11/2014 15:07:24 by Hibernate Tools 4.3.1

/**
 * InscricoesId generated by hbm2java
 */
public class InscricoesId implements java.io.Serializable {

	private int usuario;
	private int evento;

	public InscricoesId() {
	}

	public InscricoesId(int usuario, int evento) {
		this.usuario = usuario;
		this.evento = evento;
	}

	public int getUsuario() {
		return this.usuario;
	}

	public void setUsuario(int usuario) {
		this.usuario = usuario;
	}

	public int getEvento() {
		return this.evento;
	}

	public void setEvento(int evento) {
		this.evento = evento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InscricoesId))
			return false;
		InscricoesId castOther = (InscricoesId) other;

		return (this.getUsuario() == castOther.getUsuario())
				&& (this.getEvento() == castOther.getEvento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsuario();
		result = 37 * result + this.getEvento();
		return result;
	}

}
