package br.com.sysconfer.entities;

// Generated 23/11/2014 15:07:24 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Inscricoes generated by hbm2java
 */
public class Inscricoes implements java.io.Serializable {

	private InscricoesId id;
	private Date dtInscricao;
	private BigDecimal valor;

	public Inscricoes() {
	}

	public Inscricoes(InscricoesId id, Date dtInscricao, BigDecimal valor) {
		this.id = id;
		this.dtInscricao = dtInscricao;
		this.valor = valor;
	}

	public InscricoesId getId() {
		return this.id;
	}

	public void setId(InscricoesId id) {
		this.id = id;
	}

	public Date getDtInscricao() {
		return this.dtInscricao;
	}

	public void setDtInscricao(Date dtInscricao) {
		this.dtInscricao = dtInscricao;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
