package br.com.sysconfer.entities;

// Generated 29/11/2014 04:56:58 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscricoes generated by hbm2java
 */
@Entity
@Table(name = "Inscricoes", catalog = "sysconfer")
public class Inscricoes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3902901624619429113L;
	private InscricoesId id;
	private Date dtInscricao;
	private BigDecimal valor;

	public Inscricoes() {
	}

	public Inscricoes(InscricoesId id, Date dtInscricao, BigDecimal valor) {
		this.id = id;
		this.dtInscricao = dtInscricao;
		this.valor = valor;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "usuario", column = @Column(name = "usuario", nullable = false)),
			@AttributeOverride(name = "evento", column = @Column(name = "evento", nullable = false)) })
	public InscricoesId getId() {
		return this.id;
	}

	public void setId(InscricoesId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtInscricao", nullable = false, length = 19)
	public Date getDtInscricao() {
		return this.dtInscricao;
	}

	public void setDtInscricao(Date dtInscricao) {
		this.dtInscricao = dtInscricao;
	}

	@Column(name = "valor", nullable = false, precision = 6)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
