package br.com.sysconfer.entities;

// Generated 23/11/2014 15:07:24 by Hibernate Tools 4.3.1

/**
 * PerfisFuncionalidadesId generated by hbm2java
 */
public class PerfisFuncionalidadesId implements java.io.Serializable {

	private int perfil;
	private int funcionalidade;

	public PerfisFuncionalidadesId() {
	}

	public PerfisFuncionalidadesId(int perfil, int funcionalidade) {
		this.perfil = perfil;
		this.funcionalidade = funcionalidade;
	}

	public int getPerfil() {
		return this.perfil;
	}

	public void setPerfil(int perfil) {
		this.perfil = perfil;
	}

	public int getFuncionalidade() {
		return this.funcionalidade;
	}

	public void setFuncionalidade(int funcionalidade) {
		this.funcionalidade = funcionalidade;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfisFuncionalidadesId))
			return false;
		PerfisFuncionalidadesId castOther = (PerfisFuncionalidadesId) other;

		return (this.getPerfil() == castOther.getPerfil())
				&& (this.getFuncionalidade() == castOther.getFuncionalidade());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPerfil();
		result = 37 * result + this.getFuncionalidade();
		return result;
	}

}
