package br.com.sysconfer.entities;

// Generated 23/11/2014 15:07:24 by Hibernate Tools 4.3.1

/**
 * Perfis generated by hbm2java
 */
public class Perfis implements java.io.Serializable {

	private Integer idPerfis;
	private String descricao;

	public Perfis() {
	}

	public Perfis(String descricao) {
		this.descricao = descricao;
	}

	public Integer getIdPerfis() {
		return this.idPerfis;
	}

	public void setIdPerfis(Integer idPerfis) {
		this.idPerfis = idPerfis;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
