package br.com.sysconfer.entities;

// Generated 29/11/2014 04:56:58 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Perfis generated by hbm2java
 */
@Entity
@Table(name = "Perfis", catalog = "sysconfer")
public class Perfis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 636257004584218251L;
	private Integer idPerfis;
	private String descricao;

	public Perfis() {
	}

	public Perfis(String descricao) {
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPerfis", unique = true, nullable = false)
	public Integer getIdPerfis() {
		return this.idPerfis;
	}

	public void setIdPerfis(Integer idPerfis) {
		this.idPerfis = idPerfis;
	}

	@Column(name = "descricao", nullable = false, length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
