package br.com.sysconfer.entities;

// Generated 23/11/2014 15:07:24 by Hibernate Tools 4.3.1

/**
 * PerfisFuncionalidades generated by hbm2java
 */
public class PerfisFuncionalidades implements java.io.Serializable {

	private PerfisFuncionalidadesId id;

	public PerfisFuncionalidades() {
	}

	public PerfisFuncionalidades(PerfisFuncionalidadesId id) {
		this.id = id;
	}

	public PerfisFuncionalidadesId getId() {
		return this.id;
	}

	public void setId(PerfisFuncionalidadesId id) {
		this.id = id;
	}

}
