package br.com.sysconfer.entities;

// Generated 29/11/2014 04:56:58 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfisFuncionalidadesId generated by hbm2java
 */
@Embeddable
public class PerfisFuncionalidadesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2901202504821949736L;
	private int perfil;
	private int funcionalidade;

	public PerfisFuncionalidadesId() {
	}

	public PerfisFuncionalidadesId(int perfil, int funcionalidade) {
		this.perfil = perfil;
		this.funcionalidade = funcionalidade;
	}

	@Column(name = "perfil", nullable = false)
	public int getPerfil() {
		return this.perfil;
	}

	public void setPerfil(int perfil) {
		this.perfil = perfil;
	}

	@Column(name = "funcionalidade", nullable = false)
	public int getFuncionalidade() {
		return this.funcionalidade;
	}

	public void setFuncionalidade(int funcionalidade) {
		this.funcionalidade = funcionalidade;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfisFuncionalidadesId))
			return false;
		PerfisFuncionalidadesId castOther = (PerfisFuncionalidadesId) other;

		return (this.getPerfil() == castOther.getPerfil())
				&& (this.getFuncionalidade() == castOther.getFuncionalidade());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPerfil();
		result = 37 * result + this.getFuncionalidade();
		return result;
	}

}
