package br.com.sysconfer.entities;

// Generated 29/11/2014 04:56:58 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PerfisFuncionalidades generated by hbm2java
 */
@Entity
@Table(name = "Perfis_Funcionalidades", catalog = "sysconfer")
public class PerfisFuncionalidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7784289223209412366L;
	private PerfisFuncionalidadesId id;

	public PerfisFuncionalidades() {
	}

	public PerfisFuncionalidades(PerfisFuncionalidadesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "perfil", column = @Column(name = "perfil", nullable = false)),
			@AttributeOverride(name = "funcionalidade", column = @Column(name = "funcionalidade", nullable = false)) })
	public PerfisFuncionalidadesId getId() {
		return this.id;
	}

	public void setId(PerfisFuncionalidadesId id) {
		this.id = id;
	}

}
